POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR0ZXN0aSIsImlkIjoiNmEyNWM0YzMzMzUzODMzYTJiZDllMGY2IiwiaWF0IjoxNzgxNDMxNzI2fQ.FLINzxKVGFpEsiqiaJVew1ZKGyfQk65UilXZgZnjs8s

{
  "title": "Testiblogi",
  "author": "Teppo Testaaja",
  "url": "http://testiblogi.com",
  "likes": "5"
}